# Generated by Django 5.2 on 2025-04-11 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.URLField(blank=True, default=None, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('ReferredBy', models.CharField(blank=True, max_length=50, null=True)),
                ('DateOfBirth', models.DateField(blank=True, null=True)),
                ('IsMale', models.BooleanField(default=False)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Height', models.FloatField(blank=True, null=True)),
                ('Weight', models.FloatField(blank=True, null=True)),
                ('userRegDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='CLIENT', max_length=15, null=True)),
                ('AddressLine1', models.CharField(blank=True, max_length=255, null=True)),
                ('mindbody_id', models.CharField(blank=True, max_length=255, null=True)),
                ('inbody_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff_member', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
