# Generated by Django 5.2 on 2025-04-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perkville_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
