# Generated by Django 5.2 on 2025-04-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_perkville_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerkvilleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perkville_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
