version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ftf_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Lalo#4884
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-q2+!g25gusa4g8$1r_uh08+*y#*iwoeefmj15$2yzb3o+4xaad
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_NAME=ftf_backend
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Lalo#4884
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
